import * as THREE from 'three';
import {World} from '../src/world.js';
import {Battle} from '../src/battle.js';
import {createRosterModel} from '../src/characters.js';
import {ROSTER} from '../functions/shared/catalog.js';
import {useAbility,statusTick} from '../src/abilities.js';
document.querySelector('#run').onclick=()=>{
 const results=document.querySelector('#results');results.textContent='';
 const log=text=>results.textContent+=text+'\n';
 const assert=(value,message)=>{if(!value)throw new Error(message);};
 const scene=new THREE.Scene(),world=new World(scene),position=new THREE.Vector3();
 const camera=new THREE.PerspectiveCamera(62,16/9,.1,330),models=new Map();
 const input={yaw:0,pitch:0,firing:false,consumeAction:()=>false,down:()=>false};
 const noop=()=>{},ui={banner:noop,health:noop,battle:noop,cooldown:noop,kill:noop,hurt:noop,recoil:noop,toast:noop};
 const engine={world,position,camera,input,ui,move:{x:0,z:0},state:{value:'playing'},progress:{profile:{selectedCharacter:'captain'}},
  selectPlayerModel(id){this.playerVisual&&(this.playerVisual.visible=false);if(!models.has(id)){const model=createRosterModel(world,id);world.root.add(model);models.set(id,model);}this.playerVisual=models.get(id);},
  handleDeath(){this.state.value='dead';},finishMatch(){this.state.value='result';}};
 engine.selectPlayerModel('captain');let battle;
 const reset=(mode='horde',id='captain',size=4)=>{engine.progress.profile.selectedCharacter=id;engine.state.value='playing';battle.start(mode,size);scene.updateMatrixWorld(true);};
 const isolate=()=>{for(const bank of Object.values(battle.banks))bank.releaseAll();battle.player.status={};battle.player.shotTimer=0;engine.position.set(0,0,30);engine.playerVisual.position.copy(engine.position);engine.input.yaw=0;battle.player.syncHitboxes();};
 const enemyAt=(id='titan',x=0,z=24)=>{const actor=battle.banks.nightmares.acquire();battle.spawnActor(actor);actor.configure(id);actor.spawn(x,z);actor.status={};actor.shotTimer=0;actor.aiTimer=999;actor.syncHitboxes();return actor;};
 try{
  battle=new Battle(engine);reset('conquest','captain',6);assert(battle.banks.toys.active.size===5&&battle.banks.nightmares.active.size===6,'Equipos 6v6 incorrectos');
  const snapshots=[...battle.enemies.active].map(a=>[a,a.position.clone()]);for(let i=0;i<180;i++)battle.fixedUpdate(1/60);
  assert(snapshots.filter(([a,p])=>a.position.distanceTo(p)>1).length>=4,'La mayoría de bots no se movió');assert([...battle.enemies.active].every(a=>!world.blocked(a.position.x,a.position.z,0,.5)),'Un bot atravesó una cobertura');log('✓ Conquista 6v6: equipos completos, navegación y movimiento real');
  reset('confirmed','sombrio',4);assert(battle.player.team==='nightmares'&&battle.banks.nightmares.active.size===3&&battle.banks.toys.active.size===4,'Facción enemiga no jugable');log('✓ Pesadillas jugables con equipo aliado y rival 4v4');
  reset();isolate();let target=enemyAt();camera.position.set(0,1.4,35);camera.lookAt(target.body.center);camera.updateMatrixWorld();scene.updateMatrixWorld(true);
  const hp=target.health;battle.attack(battle.player);assert(battle.player.ammo===29,'El arma no consumió munición');assert(target.health<hp,'El dardo no impactó');
  battle.reloadWeapon();assert(battle.player.reload>0,'No comenzó recarga');for(let i=0;i<120;i++)statusTick(battle,battle.player,1/60);assert(battle.player.ammo===30,'No terminó recarga');log('✓ Blaster, hitboxes y recarga funcionales');
  reset();isolate();target=enemyAt('titan',0,24);assert(useAbility(battle,battle.player,0),'No lanzó granada');for(let i=0;i<100;i++)battle.updateProjectiles(1/60);assert(battle.projectiles.active.size===0,'Granada no reciclada');assert(battle.zones.active.size>0,'No quedó pintura ralentizadora');
  assert(useAbility(battle,battle.player,1)&&engine.verticalSpeed===22,'Resorte sin impulso');log('✓ Granada balística, pintura y propulsión vertical');
  for(const spec of ROSTER){
   reset('confirmed',spec.id);isolate();let other;
   if(spec.team==='toys')other=enemyAt();else{other=battle.banks.toys.acquire();battle.spawnActor(other);other.position.set(0,0,24);other.status={};other.syncHitboxes();}
   for(let slot=0;slot<3;slot++){
    battle.player.status={};battle.player.cooldowns.fill(0);battle.player.link=null;engine.position.set(0,0,30);other.position.set(0,0,24);other.health=1000;other.active=true;other.status={};other.syncHitboxes();
    const ability=spec.abilities[slot],accepted=useAbility(battle,battle.player,slot);assert(accepted===!ability.passive,`${spec.id}: ${ability.name} no funciona`);
    if(!ability.passive){assert(battle.player.cooldowns[slot]>0,`${spec.id}: cooldown ausente`);assert(!useAbility(battle,battle.player,slot),`${spec.id}: permite spam`);}
   }
  }log('✓ Las 34 habilidades activas y 2 pasivas de los 12 personajes respetan sus contratos');
  reset('confirmed','sombrio');isolate();const attacker=battle.banks.toys.acquire();battle.spawnActor(attacker);attacker.status={};
  useAbility(battle,battle.player,0);const protectedHP=battle.player.health;battle.damage(battle.player,999,attacker);battle.attack(battle.player,attacker);assert(battle.player.health===protectedHP&&battle.projectiles.active.size===0,'Invisibilidad no bloqueó daño o ataque');log('✓ Invisibilidad: inmunidad y bloqueo de ataque');
  reset('confirmed','meca');isolate();target=enemyAt('titan',0,24);battle.launch(battle.player,new THREE.Vector3(0,1.1,28),target.body.center,35,target);scene.updateMatrixWorld(true);for(let i=0;i<30;i++)battle.updateProjectiles(1/60);assert(target.health===200,'Meca debe aplicar 35 directos + 15 de explosión');
  reset('confirmed','felpa');isolate();const patient=battle.banks.toys.acquire();battle.spawnActor(patient);patient.position.set(0,0,24);patient.health=50;patient.status={};patient.syncHitboxes();battle.launch(battle.player,new THREE.Vector3(0,patient.body.center.y,25),patient.body.center,12,patient);for(let i=0;i<15;i++)battle.updateProjectiles(1/60);assert(patient.health===65,'El algodón no curó 15 HP');
  battle.zone('heal',patient.position,'toys',5,8,battle.player);battle.updateZones(1);assert(patient.health===77,'El tótem no curó 12 HP/s');log('✓ Bloques: impacto + splash; algodón y tótem: curación exacta');
  reset('confirmed','sombrio');isolate();const victim=battle.banks.toys.acquire();battle.spawnActor(victim);victim.status={poison:4};victim.poisonSource=battle.player;const poisonHP=victim.health;for(let i=0;i<240;i++)statusTick(battle,victim,1/60);assert(Math.abs(victim.health-(poisonHP-20))<.01,'Veneno no aplica 5 HP/s durante 4 s');
  reset('confirmed','gargajo');isolate();useAbility(battle,battle.player,0);battle.damage(battle.player,100,victim);assert(battle.player.shield===50&&battle.player.health===240,'Escudo no absorbió daño');log('✓ Veneno de 4 segundos y absorción del escudo viscoso');
  reset('horde');isolate();battle.player.active=false;const invader=enemyAt('gargajo',0,14);invader.route.index=4;battle.match.phase='battle';battle.match.remaining=1;const chestHP=battle.match.baseHealth;battle.updateBot(invader,.1);for(let i=0;i<90;i++)battle.updateProjectiles(1/60);assert(battle.match.baseHealth<chestHP,'IA no daña el cofre');battle.player.active=true;log('✓ La IA de horda ataca y daña el objetivo central');
  reset('confirmed');isolate();target=enemyAt();battle.damage(target,9999,battle.player);assert(battle.drops.active.size===1&&battle.match.points.toys===0,'Puntúa antes de recoger');engine.position.copy(target.position);battle.updateDrops(.1);assert(battle.match.points.toys===1&&battle.drops.active.size===0,'No confirmó núcleo');
  const ally=battle.banks.toys.acquire();battle.spawnActor(ally);ally.status={};ally.position.copy(engine.position);battle.damage(ally,9999,target);battle.updateDrops(.1);assert(battle.match.points.nightmares===0&&battle.drops.active.size===0,'No denegó batería');log('✓ Bajas: objeto físico, confirmación y denegación por aliado');
  reset('horde');for(let wave=1;wave<=10;wave++){
   battle.spawnWave();assert(battle.match.wave===wave,'Número de oleada incorrecto');const common=[...battle.enemies.active].filter(a=>!a.boss);assert(common.every(a=>a.spec.minion&&['shadowling','slimelet'].includes(a.id)),'Héroe como enemigo común');assert(common.every(a=>a.maxHealth===(a.id==='shadowling'?40:60)),'HP de esbirro incorrectos');const bosses=[...battle.enemies.active].filter(a=>a.boss);assert(bosses.length===(wave%3===0?1:0),'Jefe incorrecto');if(bosses.length)assert(bosses[0].maxHealth===1000&&bosses[0].model===bosses[0].bossModel,'Jefe no tiene 1000 HP o modelo gigante');
   for(const a of [...battle.enemies.active]){a.status={};battle.damage(a,9999,battle.player);}assert(battle.match.remaining===0,'Oleada no finalizó');battle.banks.nightmares.releaseAll();
   if(wave===1){assert(battle.match.timer===20,'Ventana de compra no dura 20 segundos');const max=battle.player.maxHealth;battle.buyUpgrade('health');assert(battle.player.maxHealth===max+20,'Mejora de vida no aplicada');}
  }assert(battle.match.phase==='won','Décima oleada no termina en victoria');log('✓ Horda completa: 10 oleadas, jefes en 3/6/9 y compra de mejoras');
  reset('conquest','sombrio');isolate();engine.position.copy(battle.objective);for(let i=0;i<3;i++){battle.updateMode(20);assert(battle.match.sector===i+1,'No avanzó sector');for(const bank of Object.values(battle.banks))bank.releaseAll();engine.position.copy(battle.objective);}
  assert(battle.match.winner==='nightmares'&&battle.weather>.8,'Conquista no finalizó o no cambió clima');log('✓ Tres sectores secuenciales, victoria atacante y cambio de clima');
  reset('confirmed');isolate();battle.damage(battle.player,9999,enemyAt());assert(engine.state.value==='dead','Falta pantalla de muerte');battle.resetPlayer();assert(battle.player.active&&battle.player.health===125&&battle.player.ammo===30,'Respawn incompleto');
  battle.stop();assert([battle.projectiles,battle.zones,battle.drops,battle.barriers,battle.portals,...Object.values(battle.banks)].every(p=>p.active.size===0),'Quedaron objetos activos');log('✓ Muerte, respawn y limpieza de pools');
  reset('confirmed');isolate();battle.player.health=50;battle.player.sinceDamage=0;battle.regenerate(4.9);assert(battle.player.health===50,'Regenera antes de 5 s');battle.regenerate(.6);assert(Math.abs(battle.player.health-55)<.001,'No cura 10 HP/s después de 5 s');target=enemyAt();battle.damage(battle.player,10,target);battle.regenerate(5);assert(Math.abs(battle.player.health-45)<.001,'El impacto no reinició espera');battle.regenerate(1);assert(Math.abs(battle.player.health-55)<.001,'Regeneración tras impacto incorrecta');battle.regenerate(100);assert(battle.player.health===125,'Sobrecuración');log('✓ Regeneración: espera 5 s, cura 10 HP/s, reinicia tras daño y respeta máximo');
  reset();isolate();target=enemyAt('titan',0,24);battle.launchGrenade(battle.player,40);const bomb=[...battle.projectiles.active][0];bomb.position.set(0,.43,25);bomb.velocity.set(0,-1,0);const startBombHP=target.health,oldPosition=target.position.clone();for(let i=0;i<60;i++)battle.updateProjectiles(1/60);assert(target.health===startBombHP&&battle.projectiles.active.size===1,'Bomba explotó antes de 1.5 s');for(let i=0;i<32;i++)battle.updateProjectiles(1/60);assert(target.health===startBombHP-40,'Splash de bomba incorrecto');assert(target.position.distanceTo(oldPosition)>1,'Bomba no empujó');assert(battle.effects.explosions.active.size===1,'No hay fuego/humo');log('✓ Bomba con mecha de 1.5 s, daño radial, empuje y explosión visible');
  battle.damageNumbers.reset();battle.damage(target,16,battle.player);battle.damage(target,32,battle.player,false,false,true);assert([...battle.damageNumbers.pool.active].some(n=>n.node.textContent==='-16'),'No aparece daño normal');assert([...battle.damageNumbers.pool.active].some(n=>n.node.textContent==='-32'&&n.node.className.includes('critical')),'No aparece crítico amarillo');battle.damageNumbers.update(1.1,camera);assert(battle.damageNumbers.pool.active.size===0,'No desaparecen números');log('✓ Números de daño normal/crítico y reciclado tras flotar');
  const ramp=world.ramps[0];assert(world.groundHeight(ramp.x,ramp.z)>1,'Rampa sin superficie');assert(world.groundHeight(ramp.x,ramp.z+ramp.d*.4)>world.groundHeight(ramp.x,ramp.z-ramp.d*.4),'Rampa no tiene pendiente');log('✓ Libros con pendiente transitable y coberturas agrupadas');
  reset('conquest');const a=battle.spawnPoint('toys'),b=battle.spawnPoint('nightmares');assert(Math.hypot(a.x-b.x,a.z-b.z)>190,'Bases demasiado cerca');for(const bank of Object.values(battle.banks))for(const actor of bank.active)assert(!battle.blocked(actor.position.x,actor.position.z,0,.5),'Spawn dentro de un objeto');log('✓ Spawns separados más de 190 metros y fuera de coberturas');
  for(const team of ['toys','nightmares'])for(let slot=0;slot<3;slot++){reset('conquest');isolate();battle.player.active=false;const actor=battle.banks[team].acquire();battle.spawnActor(actor,false,slot);let steps=0;while(actor.route.index<actor.route.points.length&&steps++<2400){battle.followRoute(actor,.05);assert(!battle.blocked(actor.position.x,actor.position.z,0,.45),'Ruta atraviesa un obstáculo');}assert(actor.route.index===actor.route.points.length,team+' ruta '+slot+' atascada: '+JSON.stringify({position:actor.position,route:actor.route}));}log('✓ Los seis corredores llegan desde las bases hasta el objetivo sin atravesar coberturas');
  reset('horde');isolate();battle.player.active=false;const melee=battle.banks.nightmares.acquire();battle.spawnActor(melee,false,0);melee.position.set(0,0,2);melee.route.index=4;melee.shotTimer=0;melee.status={};melee.syncHitboxes();const beforeCore=battle.match.baseHealth;battle.updateBot(melee,.05);assert(battle.match.baseHealth===beforeCore-10,'Mordisco no aplica 10 al cofre');battle.banks.nightmares.releaseAll();const ranged=battle.banks.nightmares.acquire();battle.spawnActor(ranged,false,2);ranged.position.set(0,0,12);ranged.route.index=4;ranged.shotTimer=0;ranged.status={};ranged.syncHitboxes();const rangedCore=battle.match.baseHealth;battle.updateBot(ranged,.05);assert(battle.projectiles.active.size===1,'Esbirro de rango no lanzó lodo');for(let i=0;i<60;i++)battle.updateProjectiles(1/60);assert(battle.match.baseHealth===rangedCore-12,'Lodo no aplica 12 al cofre');log('✓ Esbirros exclusivos: mordisco 10 y proyectil físico de lodo 12; héroes solo como jefes');
  reset('confirmed');isolate();target=enemyAt('titan',0,24);camera.position.set(0,1.4,35);camera.lookAt(target.body.center);camera.updateMatrixWorld();input.aiming=true;battle.attack(battle.player);assert(battle.recoil===.45,'ADS no reduce retroceso');assert(battle.effects.flashLights.active.size>0,'Falta luz de fogonazo');battle.effects.update(.1);assert(battle.effects.flashLights.active.size===0,'Fogonazo no se apaga');input.aiming=false;useAbility(battle,battle.player,0);assert(battle.player.status.aura>0,'Habilidad sin aura');let flatMeshes=0;battle.player.model.traverse(m=>{if(m.isMesh&&!m.material.isMeshStandardMaterial)flatMeshes++;});assert(flatMeshes===0,'Personaje usa materiales planos');log('✓ ADS integrado, fogonazo temporal y aura sobre modelo PBR');
  const probe={position:new THREE.Vector3(0,0,0),slot:0};const saved=battle.steering.colliders;const obstacle=new THREE.Mesh(new THREE.BoxGeometry(1,3,1),new THREE.MeshStandardMaterial());obstacle.position.set(.35,1.5,1.9);obstacle.updateMatrixWorld();battle.steering.colliders=[obstacle];const diverted=battle.steering.steer(probe,0,1,[]);assert(battle.steering.rays.length===3&&battle.steering.rays[0].distance<2.5,'Sensores frontales sin impacto');assert(Math.abs(diverted.x)>.8&&diverted.x<0,'No gira hacia el lado libre');battle.steering.colliders=saved;obstacle.geometry.dispose();obstacle.material.dispose();log('✓ Tres rayos a 0°/±30° evitan cobertura a menos de 2.5 m');
  log('\nTODAS LAS PRUEBAS DE INTEGRACIÓN PASARON.');
 }catch(error){log('✗ '+error.message);console.error(error);}finally{battle?.dispose();world.dispose();}
};
