import * as THREE from 'three';
import {World} from '../src/world.js';
import {Battle} from '../src/battle.js';
import {Character,createRosterModel,createMinionModel} from '../src/characters.js';
import {createStudioEnvironment} from '../src/lighting.js';
import {smoothFov} from '../src/aim.js';
import {UI} from '../src/ui.js';
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;document.body.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#162c45');scene.fog=new THREE.Fog('#162c45',90,290);const env=createStudioEnvironment(renderer);scene.environment=env.texture;scene.environmentIntensity=.6;
scene.add(new THREE.HemisphereLight('#b8d6ff','#372349',1.5));const sun=new THREE.DirectionalLight('#ffe1ba',3);sun.position.set(-15,32,24);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-40,right:40,top:40,bottom:-40,near:1,far:130});sun.shadow.normalBias=.05;scene.add(sun);const rim=new THREE.DirectionalLight('#a07cf9',2);rim.position.set(10,8,-8);scene.add(rim);
const world=new World(scene),camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.1,350),position=new THREE.Vector3(),playerVisual=createRosterModel(world,'captain');world.root.add(playerVisual);
const noop=()=>{},input={aiming:false,yaw:0,pitch:0,consumeAction:()=>false,down:()=>false};const crosshair=document.querySelector('#crosshair').getContext('2d');let aimBlend=0;
const engine={world,position,camera,input,playerVisual,move:{x:0,z:0},state:{value:'playing'},ui:{banner:noop,health:noop,battle:noop,cooldown:noop,kill:noop,hurt:noop,toast:noop,recoil:noop},handleDeath:noop,finishMatch:noop};const battle=new Battle(engine);
const stage=new THREE.Group();scene.add(stage);const floor=new THREE.Mesh(new THREE.CylinderGeometry(14,14,.3,64),world.surface('#1e354f','plastic'));floor.receiveShadow=true;floor.position.y=-.18;stage.add(floor);
const heroes=[];for(const [id,x] of [['captain',-5.4],['sombrio',-1.8],['shadowling',1.8],['slimelet',5.4]]){const minion=['shadowling','slimelet'].includes(id);const model=minion?createMinionModel(world,id):createRosterModel(world,id);stage.add(model);const actor=new Character(model,'toys','',1,1).configure(id);actor.spawn(x,0);actor.status={};model.scale.multiplyScalar(1.8);actor.size*=1.8;actor.model.rotation.y=.15;heroes.push(actor);}
let mode='gallery',time=0,accumulator=0,last=performance.now(),frames=[],lastStats=0,peakCalls=0,peakTriangles=0;
function gallery(){mode='gallery';battle.stop();world.root.visible=false;stage.visible=true;camera.position.set(0,5,13);camera.lookAt(0,1.65,0);document.querySelector('#labels').innerHTML=heroes.map(a=>'<span>'+a.name+'<small>'+a.spec.hp+' HP · '+a.spec.weapon.damage+' daño</small></span>').join('');frames=[];peakCalls=peakTriangles=0;}
function horde(){mode='horde';stage.visible=false;world.root.visible=true;battle.start('horde',4);battle.match.wave=8;battle.spawnWave();battle.player.active=false;playerVisual.visible=false;camera.position.set(90,110,145);camera.lookAt(0,0,0);document.querySelector('#labels').replaceChildren();frames=[];peakCalls=peakTriangles=0;}
document.querySelector('#gallery').onclick=gallery;document.querySelector('#horde').onclick=horde;document.querySelector('#aim').onclick=()=>{input.aiming=!input.aiming;document.querySelector('#aim').setAttribute('aria-pressed',input.aiming);};gallery();
function frame(now){const raw=(now-last)/1000,dt=Math.min(.05,raw);last=now;time+=dt;if(!document.hidden&&raw>0){frames.push(raw*1000);if(frames.length>600)frames.shift();}camera.fov=smoothFov(camera.fov,input.aiming,dt);camera.updateProjectionMatrix();aimBlend+=(Number(input.aiming)-aimBlend)*(1-Math.exp(-12*dt));UI.prototype.recoil.call({crosshair},0,aimBlend);
 if(mode==='horde'){accumulator+=dt;while(accumulator>=1/60){battle.fixedUpdate(1/60);accumulator-=1/60;}battle.update(dt);}else for(const a of heroes){a.moving=false;a.animate(dt,time);a.model.rotation.y=.15+Math.sin(time*.4)*.1;}
 renderer.render(scene,camera);peakCalls=Math.max(peakCalls,renderer.info.render.calls);peakTriangles=Math.max(peakTriangles,renderer.info.render.triangles);
 if(now-lastStats>800){lastStats=now;const sorted=[...frames].sort((a,b)=>a-b),mean=frames.reduce((a,b)=>a+b,0)/(frames.length||1);document.querySelector('#stats').textContent=(mode==='horde'?'Oleada 9 · '+[...battle.banks.nightmares.active].filter(a=>a.active).length+' enemigos vivos · '+[...battle.banks.toys.active].filter(a=>a.active).length+' aliados':'Modelos del juego · PBR, biseles, metal, plástico y auras')+' | FOV '+camera.fov.toFixed(1)+'° | '+(mean?1000/mean:0).toFixed(0)+' FPS medios · p95 '+(sorted[Math.floor(sorted.length*.95)]||0).toFixed(1)+' ms | '+peakCalls+' draw calls máx. · '+peakTriangles.toLocaleString()+' triángulos máx. · '+frames.length+' muestras';}
 requestAnimationFrame(frame);
}requestAnimationFrame(frame);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
