// Balance compartido por navegador, pruebas y servidor. Las fichas específicas
// prevalecen sobre las bandas generales de rol cuando difieren.
const a=(name,description,effect,cooldown=12,passive=false)=>({name,description,effect,cooldown,passive});
export const ROSTER=[
 {id:'captain',name:'Capitán Espuma',team:'toys',role:'Asalto',hp:125,speed:1,height:1.8,hitbox:'Mediana',model:'commando',color:'#65c9b2',unlock:{type:'free'},weapon:{name:'Blaster de Dardos',type:'hitscan',damage:16,interval:60/450,magazine:30,range:100},abilities:[a('Granada de Pintura','40 de daño en área y ralentiza 3 s.','paint',8),a('Cohete de Resorte','Propulsión vertical para alcanzar zonas altas.','spring',10),a('Recarga Táctica','Recarga un 20% más rápido en movimiento.','reload',0,true)]},
 {id:'felpa',name:'Dra. Felpa',team:'toys',role:'Soporte / Sanadora',hp:100,speed:1.05,height:1.4,hitbox:'Pequeña',model:'medic',color:'#e0ad87',unlock:{type:'level',level:3},weapon:{name:'Cañón de Algodón',type:'projectile',damage:12,heal:15,gravity:5,interval:.55,magazine:16,range:55},abilities:[a('Caja de Música','Tótem: cura 12 HP/s en un radio de 5 m.','healZone',16),a('Rayo de Costura','Vincula un aliado: +20% de defensa.','defenseLink',12),a('Nube de Incienso','Ciega enemigos durante 2 s.','blindArea',14)]},
 {id:'meca',name:'Meca-Lego',team:'toys',role:'Tanque / Constructor',hp:220,speed:.8,height:2.2,hitbox:'Grande',model:'mech',color:'#ebc266',unlock:{type:'currency',currency:'coins',cost:500},weapon:{name:'Lanzador de Bloques',type:'projectile',damage:35,splash:15,interval:.9,magazine:10,range:65,speed:22},abilities:[a('Barricada Plástica','Cobertura desplegable de 300 HP.','barricade',18),a('Modificación Torreta','Anclaje: +50% de cadencia durante 6 s.','turret',14),a('Embestida de Ladrillo','Carga y derriba: 30 de daño.','charge',12)]},
 {id:'sora',name:'Sora la Planeadora',team:'toys',role:'Francotirador / Movilidad',hp:90,speed:1.15,height:1.6,hitbox:'Pequeña',model:'glider',color:'#7cd4e5',unlock:{type:'level',level:8},weapon:{name:'Láser de Radiofrecuencia',type:'charge',damage:25,maxDamage:70,interval:1,magazine:8,range:130},abilities:[a('Despegue Turbo','Vuelo libre 4 s: Espacio asciende, Ctrl desciende.','flight',14),a('Trampa de Pilas','Mina eléctrica: paraliza 1,5 s.','mine',12),a('Escáner de Infrarrojos','Revela enemigos tras muros durante 5 s.','scan',15)]},
 {id:'dino',name:'Don Dinosaurio',team:'toys',role:'Peleador pesado',hp:180,speed:.88,height:2,hitbox:'Grande',model:'dino',color:'#80b863',unlock:{type:'currency',currency:'coins',cost:1200},weapon:{name:'Mandíbula + Chispas',type:'cone',damage:40,interval:.9,magazine:0,range:4.8},abilities:[a('Rugido de Plástico','Aliados cercanos: +15% de daño durante 5 s.','roar',14),a('Coletazo Giratorio','Golpe 360° que empuja a enemigos.','tail',10),a('Escudo de Juguete','Reduce el daño recibido un 40% durante 3 s.','guard',12)]},
 {id:'chispita',name:'Chispita',team:'toys',role:'Control / Trampero',hp:110,speed:1.1,height:1.2,hitbox:'Pequeña',model:'monkey',color:'#e2b46f',unlock:{type:'wins',team:'toys',wins:5},weapon:{name:'Ondas Acústicas',type:'cone',damage:14,interval:.35,magazine:0,range:9},abilities:[a('Platillos Aturdidores','Onda que interrumpe ataques y habilidades.','interrupt',12),a('Cuerda Explosiva','Señuelo que atrae bots y explota.','decoy',16),a('Sobrecarga','Aliados cercanos: +30% de velocidad durante 5 s.','haste',14)]},
 {id:'sombrio',name:'Sombrío',team:'nightmares',role:'Asesino / Emboscada',hp:125,speed:1.1,height:1.7,hitbox:'Pequeña',model:'claw',color:'#8970a8',unlock:{type:'free'},weapon:{name:'Dagas de Sombra',type:'projectile',damage:22,interval:.45,magazine:0,range:17,speed:35},abilities:[a('Malla de Oscuridad','Invisible e inmune 3,5 s. No puedes atacar.','cloak',15),a('Paso Espectral','Avanza hasta 8 m en la dirección de la mirada.','blink',10),a('Daga Venenosa','El próximo impacto aplica 5 HP/s durante 4 s.','poison',12)]},
 {id:'gargajo',name:'Gargajo de Baba',team:'nightmares',role:'Tanque / Control de zona',hp:240,speed:.75,height:2.3,hitbox:'Grande',model:'ogre',color:'#9973b7',unlock:{type:'level',level:3},weapon:{name:'Cañón de Lodo Tóxico',type:'projectile',damage:28,splash:28,slow:true,interval:1,magazine:10,range:55,speed:20},abilities:[a('Escudo Viscoso','150 HP de escudo; explota en baba al romperse.','slimeShield',18),a('Charco Trampa','Zona que impide saltar y usar movilidad.','rootZone',12),a('Engullir','Absorbe proyectiles frontales 2 s y recupera vida.','absorb',14)]},
 {id:'ocular',name:'Espectro Ocular',team:'nightmares',role:'Francotirador / Aéreo',hp:95,speed:1.12,height:1.5,hitbox:'Pequeña',model:'specter',color:'#a592ed',unlock:{type:'currency',currency:'essence',cost:500},weapon:{name:'Rayo Hipnótico',type:'beam',damage:10,pull:true,interval:.3,magazine:0,range:70},abilities:[a('Vuelo Sombrío','Se eleva y permanece flotando durante 6 s.','hover',14),a('Flash Cegador','Ciega enemigos en un cono frontal.','blindCone',12),a('Ojos Espías','Dos mini-ojos buscan y atacan al enemigo cercano.','eyes',18)]},
 {id:'costura',name:'Señor Costura',team:'nightmares',role:'Infiltrador / Debuffer',hp:110,speed:1,height:1.6,hitbox:'Mediana',model:'rag',color:'#b0958c',unlock:{type:'level',level:10},weapon:{name:'Agujas Malditas',type:'projectile',damage:15,homing:true,interval:.6,magazine:18,range:60,speed:18},abilities:[a('Vínculo Vudú','Transfiere al enemigo el 25% del daño recibido.','voodoo',14),a('Trampa de Hilos','Hilos que frenan y revelan enemigos.','threads',12),a('Drenaje de Vida','Roba 10 HP/s durante 4 s.','drain',14)]},
 {id:'titan',name:'Titán de Porcelana',team:'nightmares',role:'Tanque pesado / Iniciador',hp:250,speed:.7,height:2.5,hitbox:'Grande',model:'porcelain',color:'#e4ddcd',unlock:{type:'currency',currency:'essence',cost:1500},weapon:{name:'Puño de Cadenas',type:'cone',damage:42,interval:1.1,magazine:0,range:5.2},abilities:[a('Gran Grieta','Onda sísmica: aturde 1 s en área.','quake',12),a('Gancho de Cadena','Atrae al enemigo al que apuntas.','hook',10),a('Coraza Agrietada','Por debajo del 30% de vida: +25% de velocidad.','lowHealthSpeed',0,true)]},
 {id:'susurro',name:'Susurro',team:'nightmares',role:'Soporte / Controlador',hp:100,speed:1.15,height:1.3,hitbox:'Pequeña',model:'musicghost',color:'#9186c6',unlock:{type:'wins',team:'nightmares',wins:10},weapon:{name:'Ondas de Pesadilla',type:'cone',damage:12,weaken:true,interval:.45,magazine:0,range:12},abilities:[a('Melodía Aterradora','Duerme 2,5 s; el daño despierta al enemigo.','sleep',15),a('Escudo de Sombras','60 HP de escudo temporal a un aliado.','allyShield',12),a('Portal Oscuro','Conecta dos puntos para tu equipo, a 18 m.','portal',20)]}
];
export const CHARACTERS=Object.fromEntries(ROSTER.map(c=>[c.id,c]));
export const MODES={conquest:{name:'Conquista',subtitle:'Tres sectores. Una guerra por el cuarto.',description:'Las Pesadillas capturan El Escritorio, El Armario y La Cama en ese orden. Los Juguetes ganan si agotan el tiempo. Una zona disputada no progresa.',teamSize:6},confirmed:{name:'Baja confirmada',subtitle:'La baja no termina con el disparo.',description:'Recoge el objeto del rival para confirmar un punto. Recupera los de tus aliados para denegarlos. El primer equipo en llegar a 35 gana.',teamSize:4},horde:{name:'Cofre Central',subtitle:'Diez oleadas. Ningún juguete atrás.',description:'Defiende el cofre durante 10 oleadas. Un Titán de 1000 HP aparece en las oleadas 3, 6 y 9. Entre oleadas tienes 20 segundos para comprar mejoras.',teamSize:4}};
export const SECTORS=[{name:'El Escritorio',x:-48,z:54},{name:'El Armario',x:40,z:20},{name:'La Cama',x:24,z:78}];
