import * as THREE from 'three';
import {GAME} from './config.js';
import {ObjectPool} from './core.js';
import {BotSteering,resetStuck,sampleStuck} from './ai-steering.js';
import {MINIONS,waveEnemyId} from './minions.js';
import {Character,createRosterModel,createMinionModel} from './characters.js';
import {Navigation} from './navigation.js';
import {Effects} from './effects.js';
import {Match} from './match.js';
import {ROSTER,CHARACTERS,SECTORS,MODES} from '../functions/shared/catalog.js';
import {useAbility,statusTick} from './abilities.js';
import {ModeSystems} from './mode-systems.js';
import {BASES,planRoute} from './routes.js';
import {DamageNumbers} from './damage-numbers.js';
import {applyCharacterGraphics} from './graphicsSettings.js';

/** Coordinador de partida: bancos estables de actores, IA y reglas por modo. */
export class Battle extends ModeSystems {
 constructor(engine){
  super();this.engine=engine;this.world=engine.world;this.ui=engine.ui;this.match=new Match();this.effects=new Effects(this.world);this.damageNumbers=new DamageNumbers();this.base=new THREE.Vector3();this.objective=new THREE.Vector3();this.time=0;this.started=false;
  this.nav=new Navigation(GAME.worldSize,2.5,(x,z)=>this.world.blocked(x,z,0,1));this.objectiveField=this.nav.field();this.navTimer=0;this.banks={};this.steering=new BotSteering(this.world);this.cameraRight=new THREE.Vector3();this.cameraUp=new THREE.Vector3();this.coreTarget={isCore:true,body:{center:new THREE.Vector3(0,1.3,0)}};this.coreHitArea=new THREE.Sphere(this.coreTarget.body.center,1.7);
  for(const team of ['toys','nightmares']){const specs=ROSTER.filter(c=>c.team===team);this.banks[team]=new ObjectPool(team==='nightmares'?24:6,i=>{const c=specs[i%6],model=createRosterModel(this.world,c.id);this.world.root.add(model);model.visible=false;const actor=new Character(model,team,c.name,c.hp,10*c.speed).configure(c.id);actor.slot=i;actor.homeId=c.id;actor.homeModel=model;actor.label=this.makeLabel(actor);return actor;},actor=>{actor.active=false;actor.model.visible=false;actor.label.hidden=true;});}
  this.player=new Character(engine.playerVisual,'toys','Capitán Espuma',125,10).configure('captain');this.player.position=engine.position;this.actors=[this.player,...this.banks.toys.items,...this.banks.nightmares.items];
  const scanMaterial=new THREE.MeshStandardMaterial({roughness:.45,metalness:.08,color:'#e898e1',wireframe:true,transparent:true,opacity:.5,depthTest:false,depthWrite:false});
  for(const actor of this.actors){const silhouette=new THREE.Mesh(this.world.boxGeometry,scanMaterial);silhouette.visible=false;silhouette.renderOrder=10;this.world.root.add(silhouette);actor.silhouette=silhouette;}
  this.objectiveLabel=document.createElement('div');this.objectiveLabel.className='objective-marker';this.objectiveLabel.hidden=true;document.querySelector('#actor-labels').append(this.objectiveLabel);
    this.projectiles=new ObjectPool(96,()=>{const fullMaterial=new THREE.MeshStandardMaterial({roughness:.35,metalness:.08,color:'#fff5af',emissive:'#fff5af',emissiveIntensity:.55}),fastMaterial=new THREE.MeshBasicMaterial({color:'#fff5af'}),mesh=new THREE.Mesh(this.world.sphereGeometry,fullMaterial);mesh.visible=false;this.world.root.add(mesh);return {mesh,fullMaterial,fastMaterial,position:mesh.position,velocity:new THREE.Vector3(),life:0,owner:null,target:null};},p=>p.mesh.visible=false);
  for(const p of this.projectiles.items){p.bombDetails=new THREE.Group();p.mesh.add(p.bombDetails);const band=new THREE.Mesh(new THREE.TorusGeometry(1,.13,6,20),new THREE.MeshStandardMaterial({roughness:.45,metalness:.08,color:'#e9514c'}));band.rotation.x=Math.PI/2;p.bombDetails.add(band);this.world.mesh(this.world.cylinderGeometry,'#eeb75a',[0,1.2,0],[.13,.5,.13],p.bombDetails);p.spark=this.world.sphere('#ffdf70',[0,1.55,0],[.2,.2,.2],p.bombDetails);p.bombDetails.visible=false;}
  this.zones=new ObjectPool(24,()=>{const mesh=new THREE.Mesh(new THREE.CylinderGeometry(1,1,.12,32),new THREE.MeshStandardMaterial({roughness:.45,metalness:.08,color:'#b5df9e',transparent:true,opacity:.3,depthWrite:false}));mesh.visible=false;this.world.root.add(mesh);return {mesh,position:mesh.position,life:0};},z=>z.mesh.visible=false);
  for(const z of this.zones.items){z.icons=[];for(let i=0;i<2;i++){const eye=new THREE.Group();const orb=this.world.sphere('#d6c4e8',[0,0,0],[.32,.32,.32],eye);this.world.sphere('#553a70',[0,0,.3],[.12,.17,.05],eye);eye.visible=false;z.mesh.add(eye);z.icons.push(eye);}z.totem=this.world.box('#dfacb8',[0,0,0],[.18,1,.18],z.mesh);z.totem.visible=false;}
  this.dropGeometry=new THREE.OctahedronGeometry(.55);this.drops=new ObjectPool(48,()=>{const mesh=new THREE.Mesh(this.dropGeometry,new THREE.MeshStandardMaterial({color:'#edc86d',emissive:'#59451c'}));mesh.visible=false;this.world.root.add(mesh);return {mesh,position:mesh.position,life:0};},d=>d.mesh.visible=false);
  this.barriers=new ObjectPool(6,()=>{const mesh=new THREE.Mesh(this.world.boxGeometry,new THREE.MeshStandardMaterial({color:'#8bead4',transparent:true,opacity:.48}));mesh.scale.set(5,3,.7);mesh.visible=false;this.world.root.add(mesh);return {mesh,position:mesh.position,life:0,hp:300};},b=>b.mesh.visible=false);
  this.portals=new ObjectPool(4,()=>{const mesh=new THREE.Mesh(new THREE.TorusGeometry(1.4,.2,8,24),new THREE.MeshStandardMaterial({roughness:.45,metalness:.08,color:'#a887dd',transparent:true,opacity:.75}));mesh.visible=false;this.world.root.add(mesh);return {mesh,position:mesh.position,exit:new THREE.Vector3(),life:0};},p=>p.mesh.visible=false);
  this.captureRing=new THREE.Mesh(new THREE.RingGeometry(8.7,9.2,64),new THREE.MeshStandardMaterial({roughness:.45,metalness:.08,color:'#dbb880',side:THREE.DoubleSide,transparent:true,opacity:.8}));this.captureRing.rotation.x=-Math.PI/2;this.captureRing.visible=false;this.world.root.add(this.captureRing);
  this.arena=new THREE.Group();this.world.root.add(this.arena);for(const [x,z,w,d] of [[-30,40,1,60],[30,40,1,60],[0,10,60,1],[0,70,60,1]])this.world.box('#87777f',[x,2,z],[w,4,d],this.arena);this.arena.visible=false;
  this.rainData=new Float32Array(450*3);for(let i=0;i<450;i++){this.rainData[i*3]=(Math.random()-.5)*65;this.rainData[i*3+1]=Math.random()*35;this.rainData[i*3+2]=(Math.random()-.5)*65;}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(this.rainData,3));geo.boundingSphere=new THREE.Sphere(new THREE.Vector3(),65);this.rain=new THREE.Points(geo,new THREE.PointsMaterial({color:'#b6c9dc',size:.09,transparent:true,opacity:.55}));this.rain.visible=false;this.world.root.add(this.rain);
  this.ray=new THREE.Raycaster();this.hits=[];this.origin=new THREE.Vector3();this.direction=new THREE.Vector3();this.endpoint=new THREE.Vector3();this.point=new THREE.Vector3();this.muzzle=new THREE.Vector3();this.ndc=new THREE.Vector2();this.screen=new THREE.Vector3();this.temp=new THREE.Vector3();this.weather=0;this.dayColor=new THREE.Color('#729b9c');this.nightColor=new THREE.Color('#1f263f');
 }
 makeLabel(actor){const node=document.createElement('div');node.className=`actor-label ${actor.team}`;node.hidden=true;const name=document.createElement('span');name.textContent=actor.name;const health=document.createElement('i');node.append(name,health);document.querySelector('#actor-labels').append(node);actor.healthBar=health;return node;}
 get enemies(){return this.banks[this.player.team==='toys'?'nightmares':'toys'];}get allies(){return this.banks[this.player.team].items;}
 start(mode=this.engine.lobby?.mode||'horde',size=this.engine.lobby?.size||4){
  this.stop();let id=this.engine.progress?.profile.selectedCharacter||'captain';if(mode==='horde'&&CHARACTERS[id].team!=='toys'){id='captain';this.ui.toast('Cofre Central requiere Juguetes. Capitán Espuma equipado para esta partida.');}
  this.engine.selectPlayerModel?.(id);this.player.model=this.engine.playerVisual;this.player.configure(id);this.player.position=this.engine.position;this.match.reset(mode,this.player.team,size);this.started=true;this.time=0;this.navTimer=0;this.hudTimer=0;this.recoil=0;this.hit=0;this.charge=0;this.objectiveTime=0;
  this.result={id:crypto.randomUUID(),team:this.player.team,mode,character:id,kills:0,deaths:0,healing:0,objectives:0,won:false,duration:0};this.world.ambientToys.forEach(m=>m.visible=false);this.arena.visible=false;this.world.core.visible=mode==='horde';this.world.coreLabel.visible=mode==='horde';for(const p of this.world.portals){p.group.visible=mode==='horde';p.label.visible=mode==='horde';}this.captureRing.visible=mode==='conquest';this.setObjective();
  for(const team of ['toys','nightmares']){const count=mode==='horde'?(team==='toys'?size-1:0):size-(team===this.player.team?1:0);for(let i=0;i<count;i++)this.spawnActor(this.banks[team].acquire());}
  this.resetPlayer();this.ui.banner(this.player.team==='toys'?'BASE DE LOS JUGUETES':'BASE DE LAS PESADILLAS',`${MODES[mode].name} · Avanza hacia el marcador del objetivo`);this.updateHUD();
 }
 setObjective(){const sector=SECTORS[Math.min(2,this.match.sector)];if(this.match.mode==='conquest')this.objective.set(sector.x,0,sector.z);else if(this.match.mode==='confirmed')this.objective.set(0,0,40);else this.objective.copy(this.base);this.captureRing.position.copy(this.objective);this.captureRing.position.y=.14;this.nav.fill(this.objectiveField,this.objective.x,this.objective.z);}
 spawnPoint(team,index=0){const base=BASES[team],row=Math.floor((index%24)/3),x=base.x+(index%3-1)*6,z=base.z+(team==='toys'?-1:1)*row*3;return this.nearestWalkable(x,z);}
 spawnActor(actor,boss=false,index=actor.slot||0){
  const id=this.match.mode==='horde'&&actor.team==='nightmares'?(boss?'titan':waveEnemyId(1,index)):actor.homeId;
  if(boss&&!actor.bossModel){actor.bossModel=createRosterModel(this.world,'titan');this.world.root.add(actor.bossModel);}
  actor.model.visible=false;
  if(MINIONS[id]){actor.minionModels??=new Map();if(!actor.minionModels.has(id)){const model=createMinionModel(this.world,id);this.world.root.add(model);actor.minionModels.set(id,model);}actor.model=actor.minionModels.get(id);}else actor.model=boss?actor.bossModel:actor.homeModel;
  applyCharacterGraphics(actor.model,this.engine);
  actor.position=actor.model.position;actor.configure(id,boss);const p=this.spawnPoint(actor.team,index);actor.spawn(p.x,p.z);actor.status.spawn=2;actor.route=planRoute(actor.team,index,this.objective);actor.routeField=actor.routeField||this.nav.field();actor.routeGoal=new THREE.Vector3();actor.routeRefresh=0;actor.navGoal=null;resetStuck(actor);actor.portalCooldown=0;actor.aiTimer=1+Math.random()*3;actor.label.querySelector('span').textContent=boss?'JEFE · TITÁN · 1000 HP':actor.name;
 }

 resetPlayer(){const p=this.spawnPoint(this.player.team,1);this.engine.position.set(p.x,0,p.z);this.player.spawn(p.x,p.z);this.player.position=this.engine.position;this.player.maxHealth=this.player.spec.hp+(this.match.upgrades.health||0)*20;this.player.health=this.player.maxHealth;this.player.status.spawn=3;this.player.sinceDamage=0;this.player.portalCooldown=0;this.engine.verticalSpeed=0;this.engine.input.yaw=Math.atan2(this.objective.x-p.x,this.objective.z-p.z)-Math.PI;this.engine.input.pitch=.035;this.engine.playerVisual.position.copy(this.engine.position);this.engine.playerVisual.visible=true;this.player.syncHitboxes();this.charge=0;this.updateHUD();}
 stop(){this.started=false;this.objectiveLabel.hidden=true;for(const actor of this.actors)actor.silhouette.visible=false;for(const bank of Object.values(this.banks))bank.releaseAll();for(const pool of [this.projectiles,this.zones,this.drops,this.barriers,this.portals])pool.releaseAll();this.effects.reset();this.damageNumbers.reset();this.world.ambientToys.forEach(m=>m.visible=true);this.captureRing.visible=false;this.arena.visible=false;this.rain.visible=false;this.world.core.visible=true;this.world.coreLabel.visible=true;for(const p of this.world.portals){p.group.visible=true;p.label.visible=true;}this.weather=0;this.applyWeather(0);const blind=document.querySelector('#blind-overlay');if(blind)blind.style.opacity='0';}
 spawnWave(){const total=this.match.beginWave();for(let i=0;i<total;i++){const actor=this.banks.nightmares.acquire();if(!actor)throw new Error('Pool de horda agotado');const boss=i===0&&this.match.wave%3===0;if(boss)actor.originalId=actor.id;this.spawnActor(actor,boss,i);this.effects.burst(actor.position,'#c192ed',12);}this.ui.banner(`OLEADA ${this.match.wave} / 10`,this.match.wave%3===0?'¡TITÁN DE PORCELANA! · 1000 HP':`${total} pesadillas · Protege el cofre`);}
 nearestWalkable(x,z){const at=this.nav.index(x,z);if(this.nav.walkable[at])return {x,z};let best=Infinity,result={x:0,z:12};for(let i=0;i<this.nav.walkable.length;i++)if(this.nav.walkable[i]){const px=this.nav.coordinate(i%this.nav.n),pz=this.nav.coordinate(Math.floor(i/this.nav.n)),d=(x-px)**2+(z-pz)**2;if(d<best){best=d;result.x=px;result.z=pz;}}return result;}
 fixedUpdate(dt){
  if(!this.started)return;this.time+=dt;this.regenerate(dt);this.result.duration=this.time;const input=this.engine.input;for(const actor of this.actors)if(actor.active)statusTick(this,actor,dt);
  if(input.consumeAction('KeyR'))this.reloadWeapon(this.player);['KeyQ','KeyE','KeyC'].forEach((key,i)=>{if(input.consumeAction(key))useAbility(this,this.player,i);});if(input.consumeAction('Digit1'))this.buyUpgrade('damage');if(input.consumeAction('Digit2'))this.buyUpgrade('health');if(input.consumeAction('Digit3'))this.buyUpgrade('repair');
  const tap=input.consumeAction('Fire'),held=input.firing||input.down('KeyF');if(this.player.spec.weapon.type==='charge'){if(held&&!this.player.status.cloak)this.charge=Math.min(1.5,this.charge+dt);else if(this.charge>0||tap){this.attack(this.player,null,25+45*Math.min(1,this.charge/1.5));this.charge=0;}}else if(held||tap)this.attack(this.player);
  this.player.moving=!!(this.engine.move.x||this.engine.move.z);this.player.syncHitboxes();this.navTimer-=dt;if(this.navTimer<=0){this.nav.fill(this.objectiveField,this.objective.x,this.objective.z);this.navTimer=1;}
  if(this.match.mode==='horde'&&this.match.phase==='intermission'){this.match.timer-=dt;if(this.match.timer<=0)this.spawnWave();}
  for(const bank of Object.values(this.banks))for(const actor of bank.active){if(!actor.active){actor.animate(dt,this.time);actor.respawnTimer-=dt;if(this.match.mode==='horde'&&actor.team==='nightmares'&&actor.deathTime<=0){if(actor.originalId){actor.configure(actor.originalId);actor.originalId=null;}bank.release(actor);}else if(actor.respawnTimer<=0)this.spawnActor(actor);continue;}this.updateBot(actor,dt);actor.animate(dt,this.time);}
  this.updateProjectiles(dt);this.updateZones(dt);this.updateDrops(dt);this.updateBarriers(dt);this.updatePortals(dt);this.updateMode(dt);this.effects.update(dt);this.world.animateEnvironment(this.time);this.player.animate(dt,this.time);
  const rig=this.player.model.userData.rig;rig.gun.rotation.x=this.player.reload>0?-1.1+Math.sin(this.time*8)*.1:-this.engine.input.pitch;rig.gun.position.z=.35-this.recoil*.16;if(this.engine.position.y>.05)rig.legs.forEach((leg,i)=>leg.rotation.x=i?.4:-.6);
  this.hudTimer-=dt;if(this.hudTimer<=0){this.updateHUD();this.hudTimer=.1;}if(['won','lost'].includes(this.match.phase)&&this.engine.state.value==='playing'){this.result.won=this.match.phase==='won';this.engine.finishMatch(this.result.won);}
 }
 moveBot(actor,goal,dt){
  actor.wantsMove=true;if(!this.moveMultiplier(actor))return;
  let dx=goal.x-actor.position.x,dz=goal.z-actor.position.z;
  if(!this.sight(actor,goal)){
   actor.routeRefresh=(actor.routeRefresh||0)-dt;actor.routeField??=this.nav.field();
   if(!actor.navGoal||Math.hypot(actor.navGoal.x-goal.x,actor.navGoal.z-goal.z)>3||actor.routeRefresh<=0){this.nav.fill(actor.routeField,goal.x,goal.z);actor.navGoal={x:goal.x,z:goal.z};actor.routeRefresh=1;}
   this.nav.direction(actor.routeField,actor.position.x,actor.position.z,actor.direction);dx=actor.direction.x;dz=actor.direction.z;
  }
  let length=Math.hypot(dx,dz)||1;dx/=length;dz/=length;
  for(const other of this.actors)if(other!==actor&&other.active){const ox=actor.position.x-other.position.x,oz=actor.position.z-other.position.z,d=ox*ox+oz*oz;if(d>.01&&d<1.8){dx+=ox/d*.5;dz+=oz/d*.5;}}
  length=Math.hypot(dx,dz)||1;dx/=length;dz/=length;
  if(['CHASE','PATROL','CAPTURE','FLEE'].includes(actor.state))sampleStuck(actor,dt,dx,dz);
  if(actor.evadeTime>0){actor.evadeTime=Math.max(0,actor.evadeTime-dt);dx=actor.escapeDirection.x;dz=actor.escapeDirection.z;}
  else{const steered=this.steering.steer(actor,dx,dz,this.barriers.active);dx=steered.x;dz=steered.z;}
  const step=7*this.moveMultiplier(actor)*dt,x=actor.position.x,z=actor.position.z;
  // Evasion hops animate the model; they never bypass horizontal collision.
  const feet=actor.evasionHop>0?0:actor.position.y;
  if(!this.blocked(x+dx*step,z,feet,.5))actor.position.x+=dx*step;
  if(!this.blocked(actor.position.x,z+dz*step,feet,.5))actor.position.z+=dz*step;
  actor.moving=Math.hypot(actor.position.x-x,actor.position.z-z)>.001;
  if(actor.moving)actor.model.rotation.y=Math.atan2(dx,dz);
 }

 updateBot(actor,dt){
  actor.moving=false;actor.wantsMove=false;if(actor.status.stun||actor.status.sleep){resetStuck(actor);return;}if(actor.status.jump)actor.position.y=6*Math.sin(Math.PI*(1-actor.status.jump));else if(actor.status.hover)actor.position.y=Math.min(7,actor.position.y+dt*5);else if(actor.status.flight)actor.position.y=3+Math.sin(this.time)*.3;else actor.position.y=Math.max(0,actor.position.y-dt*5);
  if(actor.evasionHop>0){actor.evasionHop=Math.max(0,actor.evasionHop-dt);actor.position.y=.65*Math.sin(Math.PI*(1-actor.evasionHop/.5));}
  const wounded=actor.spec.weapon.heal?this.actors.find(a=>a!==actor&&a.active&&a.team===actor.team&&a.health<a.maxHealth*.75&&actor.position.distanceTo(a.position)<20&&this.sight(actor,a)):null;if(wounded){actor.model.rotation.y=Math.atan2(wounded.position.x-actor.position.x,wounded.position.z-actor.position.z);this.attack(actor,wounded);}
  const target=this.aimTarget(actor,false,actor.status.blind?5:35);let pickup=null,pickupDistance=Infinity;if(this.match.mode==='confirmed')for(const drop of this.drops.active){const d=actor.position.distanceTo(drop.position);if(d<pickupDistance){pickupDistance=d;pickup=drop;}}
  let decoy=null;for(const z of this.zones.active)if(z.type==='decoy'&&z.team!==actor.team&&actor.position.distanceTo(z.position)<20){decoy=z;break;}if(decoy){actor.state='CHASE';this.moveBot(actor,decoy.position,dt);return;}
  if(!target&&actor.route&&actor.route.index<actor.route.points.length){this.followRoute(actor,dt);}else if(this.match.mode==='conquest'&&actor.slot%2===0&&actor.position.distanceTo(this.objective)>6){actor.state='CAPTURE';this.moveBot(actor,this.objective,dt);if(target&&actor.position.distanceTo(target.position)<actor.spec.weapon.range&&this.sight(actor,target)){actor.model.rotation.y=Math.atan2(target.position.x-actor.position.x,target.position.z-actor.position.z);this.attack(actor,target);}}else if(pickup&&pickupDistance<18){actor.state='CHASE';this.moveBot(actor,pickup.position,dt);}else if(target){const d=actor.position.distanceTo(target.position),range=actor.spec.weapon.type==='cone'?actor.spec.weapon.range*.9:Math.min(20,actor.spec.weapon.range*.7);if(actor.health<actor.maxHealth*.15&&d<6&&actor.spec.weapon.type!=='cone'){actor.state='FLEE';this.temp.copy(actor.position).sub(target.position).multiplyScalar(2).add(actor.position);this.moveBot(actor,this.temp,dt);}else if(d>range){actor.state='CHASE';this.moveBot(actor,target.position,dt);}else actor.state='ATTACK';actor.model.rotation.y=Math.atan2(target.position.x-actor.position.x,target.position.z-actor.position.z);if(d<actor.spec.weapon.range&&this.sight(actor,target))this.attack(actor,target);
  }else if(this.match.mode==='horde'&&actor.team==='nightmares'&&actor.position.distanceTo(this.base)<(actor.spec.weapon.type==='cone'?actor.spec.weapon.range:17)&&this.sight(actor,this.base)){actor.state='ATTACK';actor.model.rotation.y=Math.atan2(-actor.position.x,-actor.position.z);this.attack(actor,this.coreTarget);}
  else{actor.state='PATROL';if(actor.position.distanceTo(this.objective)>(this.match.mode==='horde'&&actor.team==='nightmares'?Math.min(4,actor.spec.weapon.range*.75):4))this.moveBot(actor,this.objective,dt);}
  
  if(!actor.wantsMove)resetStuck(actor);actor.aiTimer-=dt;if(!actor.spec.minion&&actor.aiTimer<=0&&target){useAbility(this,actor,Math.floor(Math.random()*3));actor.aiTimer=5+Math.random()*5;}
 }
 followRoute(actor,dt){const route=actor.route;let point=route.points[route.index];if(!point)return;if(Math.hypot(actor.position.x-point.x,actor.position.z-point.z)<5){route.index++;point=route.points[route.index];if(!point)return;}const safe=this.nearestWalkable(point.x,point.z);actor.routeGoal.set(safe.x,0,safe.z);if(Math.hypot(actor.position.x-safe.x,actor.position.z-safe.z)<5){route.index++;return;}actor.state='PATROL';this.moveBot(actor,actor.routeGoal,dt);}
 regenerate(dt){if(!this.player.active)return;const before=this.player.sinceDamage||0;this.player.sinceDamage=before+dt;const healingTime=Math.max(0,this.player.sinceDamage-5)-Math.max(0,before-5);if(healingTime>0)this.heal(this.player,10*healingTime,this.player);}
 updateHUD(){this.ui.health(this.player.health,this.player.shield,this.player.maxHealth);this.ui.battle(this);['q','e','c'].forEach((key,i)=>this.ui.cooldown(key,this.player.cooldowns[i],this.player.spec.abilities[i].cooldown));}
 update(dt){this.damageNumbers.update(dt,this.engine.camera,this.engine.state.value==='playing');this.recoil=Math.max(0,this.recoil-dt*7);this.hit=Math.max(0,this.hit-dt);this.aimBlend=(this.aimBlend||0)+((this.engine.input.aiming?1:0)-(this.aimBlend||0))*(1-Math.exp(-12*dt));this.ui.recoil(this.recoil,this.aimBlend);document.querySelector('#hit-confirm').style.opacity=this.hit>0?'1':'0';const blind=document.querySelector('#blind-overlay');if(blind)blind.style.opacity=this.player.status.blind?'.94':'0';this.objectiveLabel.hidden=this.engine.state.value!=='playing'||this.match.mode==='confirmed';if(!this.objectiveLabel.hidden){this.screen.copy(this.objective);this.screen.y=5;this.screen.project(this.engine.camera);this.objectiveLabel.hidden=this.screen.z>1||Math.abs(this.screen.x)>1||Math.abs(this.screen.y)>1;this.objectiveLabel.textContent=`${this.match.mode==='horde'?'▣ COFRE':String.fromCharCode(65+Math.min(2,this.match.sector))+' · ZONA'} · ${Math.round(this.player.position.distanceTo(this.objective))} m`;this.objectiveLabel.style.transform=`translate(${(this.screen.x*.5+.5)*innerWidth}px,${(-this.screen.y*.5+.5)*innerHeight}px) translate(-50%,-100%)`;}for(const actor of this.actors){actor.silhouette.visible=actor.active&&actor.team!==this.player.team&&!!(actor.status.reveal||this.player.status.scan)&&this.engine.state.value==='playing';if(actor.silhouette.visible){actor.silhouette.position.copy(actor.body.center);actor.silhouette.scale.set(actor.body.radius*2,actor.spec.height,actor.body.radius*1.3);}if(!actor.label)continue;if(!actor.active||actor.status.cloak||this.engine.state.value!=='playing'){actor.label.hidden=true;continue;}this.screen.copy(actor.head.center);this.screen.y+=.5;this.screen.project(this.engine.camera);actor.label.hidden=!(this.screen.z<1&&this.screen.z>-1&&Math.abs(this.screen.x)<1.1&&Math.abs(this.screen.y)<1.1&&(actor.team===this.player.team||actor.status.reveal||this.player.status.scan||this.sight(this.player,actor)));if(actor.label.hidden)continue;actor.label.style.transform=`translate(${(this.screen.x*.5+.5)*innerWidth}px,${(-this.screen.y*.5+.5)*innerHeight}px) translate(-50%,-100%)`;actor.healthBar.style.width=`${actor.health/actor.maxHealth*100}%`;actor.label.dataset.state=actor.state;}}
 dispose(){this.stop();this.steering.dispose();this.damageNumbers.dispose();this.objectiveLabel.remove();for(const actor of this.actors)actor.label?.remove();}
}
