import * as THREE from 'three';
import {Combat} from './combat.js';
import {SECTORS} from '../functions/shared/catalog.js';
export class ModeSystems extends Combat {
 zone(type,position,team,radius,life,owner){const z=this.zones.acquire();if(!z)return;z.type=type;z.position.copy(position);z.position.y=.12;z.team=team;z.owner=owner;z.radius=radius;z.life=life;z.tick=0;z.mesh.scale.set(radius,1,radius);z.mesh.material.color.set(type==='heal'?'#a6efa5':type==='mine'?'#e6db83':team==='toys'?'#f0a08c':'#a588d1');z.mesh.visible=true;z.icons.forEach(e=>e.visible=type==='eyes');z.totem.visible=['heal','decoy'].includes(type);z.totem.scale.set(1.3/radius,1.4,1.3/radius);z.totem.position.y=.7;}
 updateZones(dt){for(const z of this.zones.active){z.life-=dt;z.tick-=dt;z.mesh.material.opacity=z.type==='eyes'?0:z.type==='threads'?.035:.23+Math.sin(this.time*3)*.05;z.icons.forEach((eye,i)=>{const a=this.time*2+i*Math.PI;eye.position.set(Math.cos(a)*2/z.radius,1.7,Math.sin(a)*2/z.radius);eye.scale.set(1/z.radius,1,1/z.radius);});
  if(z.type==='decoy'&&z.life<=0){for(const other of this.actors)if(other.active&&other.team!==z.team&&other.position.distanceTo(z.position)<z.radius)this.damage(other,55,z.owner);this.effects.burst(z.position,'#f8d591',25);}
  for(const actor of this.actors)if(actor.active&&actor.position.distanceTo(z.position)<z.radius){const enemy=actor.team!==z.team;if(z.type==='heal'&&!enemy)this.heal(actor,12*dt,z.owner);if(enemy&&['slow','root','threads'].includes(z.type)){actor.status.slow=.25;if(z.type==='root')actor.status.root=.25;if(z.type==='threads')actor.status.reveal=3;}if(enemy&&z.type==='mine'){actor.status.stun=1.5;this.damage(actor,20,z.owner);z.life=0;}if(enemy&&z.type==='eyes'&&z.tick<=0){this.damage(actor,8,z.owner);this.effects.tracer(z.position,actor.body.center,'#c7a4fc');z.tick=.6;}}
  if(z.life<=0)this.zones.release(z);
 }}
 placeBarrier(actor){const b=this.barriers.acquire();if(!b)return;b.position.copy(this.ahead(actor,3));b.position.y=1.5;b.hp=300;b.life=15;b.mesh.visible=true;}
 updateBarriers(dt){for(const b of this.barriers.active){b.life-=dt;if(b.life<=0||b.hp<=0){this.effects.burst(b.position,'#a4dfe8',12);this.barriers.release(b);}}}
 placePortal(actor){const end=this.ahead(actor,18),safe=this.nearestWalkable(end.x,end.z);for(const reverse of [false,true]){const p=this.portals.acquire();if(!p)break;p.position.copy(reverse?new THREE.Vector3(safe.x,0,safe.z):actor.position);p.position.y=1.5;p.exit.copy(reverse?actor.position:new THREE.Vector3(safe.x,0,safe.z));p.team=actor.team;p.life=12;p.mesh.visible=true;}}
 updatePortals(dt){for(const p of this.portals.active){p.life-=dt;p.mesh.rotation.z+=dt;for(const actor of this.actors)if(actor.active&&actor.team===p.team&&!actor.portalCooldown&&Math.hypot(actor.position.x-p.position.x,actor.position.z-p.position.z)<1.4){actor.position.copy(p.exit);actor.portalCooldown=2;}if(p.life<=0)this.portals.release(p);}}
 dropItem(actor){const d=this.drops.acquire();if(!d)return;d.team=actor.team;d.mesh.geometry=actor.team==='toys'?this.world.cylinderGeometry:this.dropGeometry;d.mesh.scale.set(actor.team==='toys'?.35:1,actor.team==='toys'?.75:1,actor.team==='toys'?.35:1);d.position.copy(actor.position);d.position.y=.7;d.life=25;d.mesh.material.color.set(actor.team==='toys'?'#fbd776':'#ad7ee9');d.mesh.visible=true;}
 updateDrops(dt){for(const d of this.drops.active){d.life-=dt;d.mesh.rotation.y+=dt*2;d.position.y=.7+Math.sin(this.time*3)*.15;for(const actor of this.actors)if(actor.active&&Math.hypot(actor.position.x-d.position.x,actor.position.z-d.position.z)<1.6){if(actor.team!==d.team){this.match.confirm(actor.team);if(actor===this.player)this.result.objectives++;}else if(actor===this.player)this.result.objectives++;if(actor===this.player)this.ui.toast(actor.team===d.team?'Baja denegada':'Baja confirmada +1');this.drops.release(d);break;}if(d.life<=0)this.drops.release(d);}}
 updateMode(dt){
  if(this.match.mode==='conquest'){let attackers=0,defenders=0;for(const actor of this.actors)if(actor.active&&!actor.status.cloak&&actor.position.distanceTo(this.objective)<9){if(actor.team==='nightmares')attackers++;else defenders++;}
   const changed=this.match.captureTick(dt,attackers,defenders);if(changed&&this.player.team==='nightmares')this.result.objectives+=3;
   if(changed&&this.match.sector<3){this.setObjective();for(const bank of Object.values(this.banks))for(const actor of bank.active)this.spawnActor(actor);this.resetPlayer();this.ui.banner(`SECTOR ${this.match.sector+1} · ${SECTORS[this.match.sector].name}`,'Nuevo objetivo: avanza desde la base de tu equipo');}
   if(this.player.active&&this.player.position.distanceTo(this.objective)<9){this.objectiveTime=(this.objectiveTime||0)+dt;if(this.objectiveTime>=10){this.result.objectives++;this.objectiveTime=0;}}
   this.weather=THREE.MathUtils.lerp(this.weather,Math.min(1,(this.match.sector+this.match.capture/100)/2),Math.min(1,dt*.7));this.captureRing.material.color.set(this.match.contested?'#f2ce85':attackers?'#c08deb':'#9fd7b4');
  }else this.weather=THREE.MathUtils.lerp(this.weather,this.match.mode==='horde'?.4:0,dt*.3);
  this.applyWeather(this.weather);this.rain.visible=this.weather>.55;if(this.rain.visible){this.rain.position.copy(this.engine.position);for(let i=0;i<450;i++){this.rainData[i*3+1]-=dt*24;if(this.rainData[i*3+1]<0)this.rainData[i*3+1]=35;}this.rain.geometry.attributes.position.needsUpdate=true;}
 }
 applyWeather(value){if(!this.engine.sun)return;this.engine.sun.intensity=3.3-value*2.6;this.engine.ambientLight.intensity=.5-value*.25;this.engine.scene.background.copy(this.dayColor).lerp(this.nightColor,value);this.engine.scene.fog.color.copy(this.engine.scene.background);}
 buyUpgrade(kind,actor=this.player){if(this.squadSync&&!this.squadSync.leader&&actor===this.player){const index=['damage','health','repair'].indexOf(kind);if(index<0){this.ui.toast('Mejora inválida');return;}this.squadSync.upgradeSeq[index]++;this.publishSquadPlayer();return;}try{this.match.buyUpgrade(kind);if(kind==='health'){actor.maxHealth+=20;actor.health+=20;}this.ui.toast('Mejora comprada');this.updateHUD();}catch(e){this.ui.toast(e.message);}}
}
